apiVersion: v1
kind: Namespace
metadata:
  name: debug
  labels:
    istio-injection: enabled
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: anquan
    version: v1
  name: anquan-v1
  namespace: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anquan
      version: v1
  template:
    metadata:
      labels:
        app: anquan
        version: v1
    spec:
      containers:
        - image: hkccr.ccs.tencentyun.com/foxzhong/futu_debug:v1
          imagePullPolicy: Always
          name: anquan
          ports:
            - containerPort: 7000
              protocol: TCP
          env:
          - name: SERVICE
            value: anquan
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: anquan
  name: anquan
  namespace: debug
spec:
  ports:
    - name: http
      port: 7000
      protocol: TCP
  selector:
    app: anquan
  type: ClusterIP
